# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - todo-api-rn

on:
  push:
    branches:
      - ravi_dev
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build Shared Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Shared
        working-directory: ./packages/models
        id: shared-output
        run: |
          npm install
          npm run build
      
      # Build the API and link the shared library
      - name: API
        working-directory: ./src/api
        run: |
          npm install
          npm run build
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo-api-rn'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4659A726DF24BB9A2CCA14DC8E45F3A }}
          package: .
