# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - todo-api-rn

on:
  push:
    branches:
      - test_rn
  workflow_dispatch:

jobs:
  build-shared:
    name: Build Shared Library
    runs-on: ubuntu-latest
    outputs:
      shared-path: ${{ env.output-path }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build the shared
        working-directory: ./packages/models
        id: shared-output
        run: |
          npm install
          npm run build # Ensure a "build" script exists in shared's package.json
          echo "output-path=$(pwd)/dist" >> $GITHUB_ENV
      
  build-api:
    name: Deploy API to Azure App Service
    needs: build-shared
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          
      # Build the API and link the shared library
      - name: Install Dependencies and Link Shared
        working-directory: ./src/api
        run: |
          npm install
          npm link ${{env.output-path}} # Link built shared library
          npm run build        
     
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: todo-api-rn
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./src/api/build