name: Main Branch Full Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    name: main deploy web and api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Shared
        working-directory: ./packages/models
        id: shared-output
        run: |
          npm install
          npm run build
      
      # Build the API and link the shared library
      - name: Build API
        working-directory: ./src/api
        run: |
          npm install
          npm run build
      - name: zip
        run: zip -r app.zip .
      
      - name: 'Deploy API to AP1'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo-api-rn'
          slot-name: 'Production'
          publish-profile: ${{ secrets.API1 }}
          package: ./app.zip

      - name: build web
        working-directory: ./src/web
        run: |
          npm install
          npm i -g serve
          npm run build
        
      - name: 'Deploy to web'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todo-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.WEB1 }}
          package: ./src/web/dist